apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: observability
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:0.131.0
  config:
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'kubernetes-pods'
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - action: keep
                  source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                  regex: 'true'
                - action: replace
                  source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                  target_label: __metrics_path__
                  regex: (.+)
                - action: replace
                  source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
                  regex: (.+?)(?::\d+)?;(\d+)
                  replacement: $1:$2
                  target_label: __address__
    processors:
      batch: {}
      memory_limiter:
        check_interval: 1s
        limit_mib: 512
        spike_limit_mib: 128
      resourcedetection:
        detectors: [env, system]
      attributes:
        actions:
          - key: service.name
            action: upsert
            from_attribute: k8s.pod.name
    exporters:
      logging: { loglevel: info }
      prometheusremotewrite/mimir:
        endpoint: http://lgtm-mimir-nginx.monitoring.svc:80/api/v1/push
        tls:
          insecure: true
      otlphttp/loki:
        compression: gzip
        endpoint: http://lgtm-loki-gateway.monitoring.svc:80
        tls:
          insecure: true
      otlphttp/tempo:
        compression: gzip
        endpoint: http://lgtm-tempo-distributor.monitoring.svc:4318
        tls:
          insecure: true
    service:
      telemetry:
        logs:
          level: info
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlphttp/tempo, logging]
        metrics:
          receivers: [otlp, prometheus]
          processors: [memory_limiter, batch]
          exporters: [prometheusremotewrite/mimir]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/loki]
