apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts/
    chart: victoria-metrics-k8s-stack
    targetRevision: 0.45.0
    helm:
      releaseName: vms
      values: |
        victoria-metrics-operator:
          enabled: true
        prometheus:
          enabled: true
        vmsingle:
          enabled: true
          spec:
            retentionPeriod: 7d
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
