apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: 37.0.0
    helm:
      releaseName: traefik
      values: |
        # OpenTelemetry: push Traefik metrics and traces to the cluster Collector
        metrics:
          otlp:
            enabled: true
            # add useful labels for correlation
            addEntryPointsLabels: true
            addRoutersLabels: true
            addServicesLabels: true
            http:
              enabled: true
              # OTLP/HTTP endpoint exposed by the OpenTelemetry Collector
              endpoint: "http://otel-collector-collector.observability.svc:4318/v1/metrics"

        tracing:
          # optional but recommended naming
          serviceName: traefik
          sampleRate: 1.0
          otlp:
            enabled: true
            http:
              enabled: true
              # OTLP/HTTP traces endpoint on the Collector
              endpoint: "http://otel-collector-collector.observability.svc:4318/v1/traces"

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
